"""Object storage for uploaded and generated documents.

Two backends behind one small interface, chosen by ``STORAGE_BACKEND``:

* ``local``: files under ``STORAGE_LOCAL_ROOT`` (a Docker volume shared by the API and the
  worker). Downloads are streamed by the API after its permission check.
* ``s3``: any S3-compatible store (AWS, Wasabi, Backblaze B2, MinIO). The bucket stays
  private; downloads are short-lived signed URLs that force a file download.

Keys are generated by the application (``uploads/<org>/<id>``), never taken from user input,
and are still validated so a bad key can never escape the storage root.
"""

from __future__ import annotations

import asyncio
import os
import re
import tempfile
from pathlib import Path
from typing import Any, Protocol
from urllib.parse import quote

from app.core.config import Settings, StorageBackendKind

_KEY = re.compile(r"^[a-z]+(/[A-Za-z0-9._-]+)+$")


class StorageError(RuntimeError):
    pass


def check_key(key: str) -> str:
    if not _KEY.fullmatch(key) or any(part in {".", ".."} for part in key.split("/")):
        raise StorageError(f"invalid storage key {key!r}")
    return key


def content_disposition(filename: str) -> str:
    """``attachment`` with an ASCII fallback and the exact UTF-8 name (RFC 6266)."""
    ascii_name = filename.encode("ascii", "replace").decode().replace('"', "_").replace("?", "_")
    return f"attachment; filename=\"{ascii_name}\"; filename*=UTF-8''{quote(filename, safe='')}"


class ObjectStorage(Protocol):
    name: str

    async def put(self, key: str, data: bytes, content_type: str) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...

    async def move(self, src: str, dst: str) -> None: ...

    async def signed_download_url(self, key: str, filename: str, content_type: str) -> str | None:
        """A time-limited URL the browser can fetch directly, or ``None`` when the API
        must stream the file itself."""
        ...


class LocalStorage:
    name = "local"

    def __init__(self, root: str) -> None:
        self.root = Path(root)

    def _path(self, key: str) -> Path:
        path = (self.root / check_key(key)).resolve()
        if not path.is_relative_to(self.root.resolve()):
            raise StorageError(f"invalid storage key {key!r}")
        return path

    def _put(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        # Write then rename, so a reader never sees half a file.
        fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".upload-")
        try:
            with os.fdopen(fd, "wb") as fh:
                fh.write(data)
            os.chmod(tmp, 0o600)
            os.replace(tmp, path)
        except BaseException:
            Path(tmp).unlink(missing_ok=True)
            raise

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        await asyncio.to_thread(self._put, key, data)

    async def get(self, key: str) -> bytes:
        try:
            return await asyncio.to_thread(self._path(key).read_bytes)
        except FileNotFoundError:
            raise StorageError(f"missing object {key!r}") from None

    async def delete(self, key: str) -> None:
        await asyncio.to_thread(self._path(key).unlink, missing_ok=True)

    def _move(self, src: str, dst: str) -> None:
        target = self._path(dst)
        target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        os.replace(self._path(src), target)

    async def move(self, src: str, dst: str) -> None:
        await asyncio.to_thread(self._move, src, dst)

    async def signed_download_url(self, key: str, filename: str, content_type: str) -> str | None:
        return None


class S3Storage:
    name = "s3"

    def __init__(self, settings: Settings) -> None:
        import boto3
        from botocore.config import Config

        secret = settings.storage_s3_secret_access_key
        self.bucket = settings.storage_s3_bucket or ""
        self.expires = settings.storage_signed_url_seconds
        self.client: Any = boto3.client(
            "s3",
            region_name=settings.storage_s3_region,
            endpoint_url=settings.storage_s3_endpoint_url,
            aws_access_key_id=settings.storage_s3_access_key_id,
            aws_secret_access_key=secret.get_secret_value() if secret else None,
            config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
        )

    async def put(self, key: str, data: bytes, content_type: str) -> None:
        await asyncio.to_thread(
            self.client.put_object,
            Bucket=self.bucket,
            Key=check_key(key),
            Body=data,
            ContentType=content_type,
            ServerSideEncryption="AES256",
        )

    async def get(self, key: str) -> bytes:
        def _get() -> bytes:
            response = self.client.get_object(Bucket=self.bucket, Key=check_key(key))
            body: bytes = response["Body"].read()
            return body

        return await asyncio.to_thread(_get)

    async def delete(self, key: str) -> None:
        await asyncio.to_thread(self.client.delete_object, Bucket=self.bucket, Key=check_key(key))

    async def move(self, src: str, dst: str) -> None:
        await asyncio.to_thread(
            self.client.copy_object,
            Bucket=self.bucket,
            Key=check_key(dst),
            CopySource={"Bucket": self.bucket, "Key": check_key(src)},
            ServerSideEncryption="AES256",
        )
        await self.delete(src)

    async def signed_download_url(self, key: str, filename: str, content_type: str) -> str | None:
        url: str = await asyncio.to_thread(
            self.client.generate_presigned_url,
            "get_object",
            Params={
                "Bucket": self.bucket,
                "Key": check_key(key),
                "ResponseContentDisposition": content_disposition(filename),
                "ResponseContentType": content_type,
            },
            ExpiresIn=self.expires,
        )
        return url


def create_storage(settings: Settings) -> ObjectStorage:
    if settings.storage_backend == StorageBackendKind.S3:
        return S3Storage(settings)
    return LocalStorage(settings.storage_local_root)
