"""Privacy and legal (Milestone 19).

* ``policy_acceptance``: agreement to a version of the Terms of Use or Privacy Policy
  (append-only for the application: SELECT and INSERT only).
* ``privacy_request``: access, correction, deletion and complaint requests, and the deletion
  queued when someone closes their account.
* Permission ``privacy.manage`` for ADMIN and SUPERADMIN.

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-10
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "approvalready_rw"

PRIVILEGES = {
    "policy_acceptance": "SELECT, INSERT",
    "privacy_request": "SELECT, INSERT, UPDATE",
}
PERMISSION = "privacy.manage"
PERMISSION_DESCRIPTION = "Read and answer privacy requests (staff)"
PERMISSION_ROLES = ["ADMIN", "SUPERADMIN"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_acceptance",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("document", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ip", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "document IN ('terms', 'privacy')", name=op.f("ck_policy_acceptance_document_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_policy_acceptance_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_acceptance")),
    )
    op.create_index(
        "ix_policy_acceptance_user_document",
        "policy_acceptance",
        ["user_id", "document", "version"],
        unique=False,
    )
    op.create_table(
        "privacy_request",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="OPEN", nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('ACCESS', 'CORRECTION', 'DELETION', 'COMPLAINT', 'OTHER')",
            name=op.f("ck_privacy_request_kind_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('CONTACT_FORM', 'ACCOUNT_CLOSED')",
            name=op.f("ck_privacy_request_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'DONE', 'DECLINED')", name=op.f("ck_privacy_request_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["app_user.id"],
            name=op.f("fk_privacy_request_resolved_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_privacy_request_user_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_privacy_request")),
    )
    op.create_index(
        "ix_privacy_request_status_due", "privacy_request", ["status", "due_at"], unique=False
    )
    # ### end Alembic commands ###
    for table, privileges in PRIVILEGES.items():
        op.execute(f"GRANT {privileges} ON {table} TO {APP_ROLE}")
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO permission (id, key, description) "
            "VALUES (gen_random_uuid(), :key, :description)"
        ),
        {"key": PERMISSION, "description": PERMISSION_DESCRIPTION},
    )
    conn.execute(
        sa.text(
            "INSERT INTO role_permission (role_id, permission_id) "
            "SELECT r.id, p.id FROM role r, permission p "
            "WHERE r.key = ANY(:roles) AND p.key = :permission"
        ),
        {"roles": PERMISSION_ROLES, "permission": PERMISSION},
    )


def downgrade() -> None:
    op.execute(
        "DELETE FROM role_permission WHERE permission_id IN "
        "(SELECT id FROM permission WHERE key = 'privacy.manage')"
    )
    op.execute("DELETE FROM permission WHERE key = 'privacy.manage'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_privacy_request_status_due", table_name="privacy_request")
    op.drop_table("privacy_request")
    op.drop_index("ix_policy_acceptance_user_document", table_name="policy_acceptance")
    op.drop_table("policy_acceptance")
    # ### end Alembic commands ###
