"""Refunds for paid reviews (Milestone 22).

* ``refund`` (tenant, forced RLS): money given back on a payment, recorded before it is
  sent to Stripe. What is refunded and why never changes (trigger); only how far sending it
  got does. Rows are never deleted.
* ``pending_refunds()``: SECURITY DEFINER, ids of refunds still waiting to be sent, for the
  worker's sweep.
* Permission ``billing.refund`` (ADMIN, SUPERADMIN): refund a paid review.

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-10
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "approvalready_rw"
TENANT_PREDICATE = "organisation_id = nullif(current_setting('app.current_org', true), '')::uuid"

NEW_PERMISSIONS = {
    "billing.refund": "Refund paid reviews (staff)",
}
PERMISSION_ROLES = {
    "billing.refund": ("ADMIN", "SUPERADMIN"),
}

REFUND_GUARD = """
CREATE FUNCTION refund_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'a refund cannot be deleted';
    END IF;
    IF (NEW.organisation_id, NEW.payment_id, NEW.amount_cents, NEW.currency, NEW.reason,
        NEW.note, NEW.created_by, NEW.created_at)
        IS DISTINCT FROM
       (OLD.organisation_id, OLD.payment_id, OLD.amount_cents, OLD.currency, OLD.reason,
        OLD.note, OLD.created_by, OLD.created_at) THEN
        RAISE EXCEPTION 'a refund never changes; only how far sending it got is recorded';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER refund_immutable
    BEFORE UPDATE OR DELETE ON refund
    FOR EACH ROW EXECUTE FUNCTION refund_guard();
"""

PENDING_FUNCTION = """
CREATE FUNCTION pending_refunds(older_than interval)
RETURNS TABLE (id uuid, organisation_id uuid)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
    SELECT r.id, r.organisation_id FROM refund r
     WHERE r.status = 'PENDING' AND r.updated_at < now() - older_than
     ORDER BY r.updated_at
     LIMIT 500
$$;
REVOKE ALL ON FUNCTION pending_refunds(interval) FROM PUBLIC;
"""


def _seed_permissions() -> None:
    conn = op.get_bind()
    for key, description in NEW_PERMISSIONS.items():
        conn.execute(
            sa.text(
                "INSERT INTO permission (id, key, description) "
                "VALUES (gen_random_uuid(), :key, :description)"
            ),
            {"key": key, "description": description},
        )
        conn.execute(
            sa.text(
                "INSERT INTO role_permission (role_id, permission_id) "
                "SELECT r.id, p.id FROM role r, permission p "
                "WHERE r.key = ANY(:roles) AND p.key = :permission"
            ),
            {"roles": list(PERMISSION_ROLES[key]), "permission": key},
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refund",
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("status", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column("stripe_refund_id", sa.String(length=255), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "reason <> 'STAFF' OR note IS NOT NULL", name=op.f("ck_refund_staff_gives_reason")
        ),
        sa.CheckConstraint(
            "reason IN ('REVIEW_CANCELLED', 'PAID_AFTER_CANCEL', 'STAFF')",
            name=op.f("ck_refund_reason_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'SUBMITTED', 'SUCCEEDED', 'FAILED')",
            name=op.f("ck_refund_status_valid"),
        ),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_refund_amount_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_refund_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "payment_id"],
            ["payment.organisation_id", "payment.id"],
            name=op.f("fk_refund_organisation_id_payment"),
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_refund_organisation_id_organisation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refund")),
        sa.UniqueConstraint("organisation_id", "id", name=op.f("uq_refund_organisation_id_id")),
        sa.UniqueConstraint("stripe_refund_id", name=op.f("uq_refund_stripe_refund_id")),
    )
    op.create_index(op.f("ix_refund_organisation_id"), "refund", ["organisation_id"], unique=False)
    op.create_index("ix_refund_payment_id", "refund", ["payment_id"], unique=False)
    op.create_index("ix_refund_status", "refund", ["status", "updated_at"], unique=False)
    # ### end Alembic commands ###
    op.execute(REFUND_GUARD)
    op.execute("ALTER TABLE refund ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE refund FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON refund "
        f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
    )
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON refund TO {APP_ROLE}")
    op.execute(PENDING_FUNCTION)
    op.execute(f"GRANT EXECUTE ON FUNCTION pending_refunds(interval) TO {APP_ROLE}")
    _seed_permissions()


def downgrade() -> None:
    op.execute(
        "DELETE FROM role_permission WHERE permission_id IN "
        "(SELECT id FROM permission WHERE key = 'billing.refund')"
    )
    op.execute("DELETE FROM permission WHERE key = 'billing.refund'")
    op.execute("DROP FUNCTION pending_refunds(interval)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refund_status", table_name="refund")
    op.drop_index("ix_refund_payment_id", table_name="refund")
    op.drop_index(op.f("ix_refund_organisation_id"), table_name="refund")
    op.drop_table("refund")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION refund_guard()")
